title: "METAROBOT 연구회 | MARS"
description: "로봇 제작 과정 및 포트폴리오 아카이브"
url: "https://textnecklee.github.io"
baseurl: "/mars.github.io" # 저장소 이름이 mars.github.io 라면 이게 필요합니다.

# 테마 설정 (Minimal Mistakes 원격 적용)
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache  # <- 이 줄이 반드시 있어야 합니다!

# 작성자(연구회) 정보
author:
  name   : "Metarobot labotary"  # 동아리 이름
  avatar : "https://textnecklee.github.io/mars.github.io/assets/images/logo.jpg" # 아까 올린 로고 사진 경로
  bio    : "로봇 연구회" # 간단한 소개
  location : "KoreaTech, KR" # 학교/지역
  links:
    - label: "Email :  metarobot0710@gmail.com"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:metarobot0710@gmail.com" # 동아리 대표 메일
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/textnecklee"
# 검색 기능 설정
search: true
search_full_content: true # 글 내용까지 전부 검색할지 여부
search_provider: lunr # 별도 설치 필요 없는 가벼운 검색 엔진

# 파비콘 설정 (브라우저 탭 아이콘)
favicon: "/mars.github.io/assets/images/logo.jpg"

# 모양 설정
minimal_mistakes_skin: "air" # 취향에 따라 air, contrast, sunrise 등으로 변경 가능