title: "Metarobot 연구회"
description: "로봇 제작 과정 및 포트폴리오 아카이브"
url: "https://textnecklee.github.io"
baseurl: "/mars.github.io" # 저장소 이름이 mars.github.io 라면 이게 필요합니다.

# 테마 설정 (Minimal Mistakes 원격 적용)
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache  # <- 이 줄이 반드시 있어야 합니다!

# 작성자(연구회) 정보
author:
  name   : "Metarobot Team"  # 동아리 이름
  avatar : "https://textnecklee.github.io/mars.github.io/assets/images/logo.jpg" # 아까 올린 로고 사진 경로
  bio    : "자율주행 및 로봇 제어 연구회" # 간단한 소개
  location : "KoreaTech, KR" # 학교/지역
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your-email@example.com" # 동아리 대표 메일
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/textnecklee"

# 모양 설정
minimal_mistakes_skin: "default" # 취향에 따라 air, contrast, sunrise 등으로 변경 가능